In [1]:
import numpy as np
from pandas import DataFrame
from warnings import filterwarnings as message
message(action='ignore')



In [2]:
matrix=DataFrame(np.array([[2,-1,0],
                           [-1,2,-1],
                           [0,-1,2]]))
matrix

0  1  2
0  2 -1  0
1 -1  2 -1
2  0 -1  2

array([[ 0, -2,  5],
       [-1,  1,  5],
       [ 1, -1,  0]])

In [58]:
matrix=DataFrame(np.array([[4,-1,1],
                           [-2,2,-1],
                           [0,-1,6]]))
matrix

0  1  2
0  4 -1  1
1 -2  2 -1
2  0 -1  6

In [16]:

import numpy as np
import pandas as pd

class Fadeev:
    def __init__(self, matrix):
        self.matrix = matrix

    @property
    def matrix(self):
        return self.__matrix

    @matrix.setter
    def matrix(self, other_matrix):
        if other_matrix.shape == (3, 3):
            self.__matrix = other_matrix
        else:
            raise ValueError("Matrix must be 3x3")

    @staticmethod
    def trace(matrix):
        return np.array(matrix).trace()

    @staticmethod
    def get_identity_matrix(size=3):
        return np.eye(size)

    
    def method(self, limit=500000):

        A,B,P=[],[],[]
        moment=0
        while True:
            moment += 1
            A.append(self.matrix.dot(B[-1]) if moment!=1 else self.matrix)
            P.append(self.trace(A[-1]) / (moment))
            B.append(A[-1] - P[-1] * self.get_identity_matrix())
            if np.all(B[-1] == 0) or moment > limit:
                return A, B, P
            
            
    
    
    

In [17]:
matrix=np.random.randint(-2,6,[3,3])
fadeev=Fadeev(matrix=matrix)
A,B,P=fadeev.method()

In [18]:
A

[array([[ 2, -2,  5],
        [ 1,  1,  5],
        [ 1, -1,  0]]),
 array([[  1.,  -5., -15.],
        [  5.,  -9.,  -5.],
        [ -2.,   0.,   0.]]),
 array([[-10.,   0.,   0.],
        [  0., -10.,   0.],
        [  0.,   0., -10.]])]

In [19]:
B

[array([[-1., -2.,  5.],
        [ 1., -2.,  5.],
        [ 1., -1., -3.]]),
 array([[  5.,  -5., -15.],
        [  5.,  -5.,  -5.],
        [ -2.,   0.,   4.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])]

In [83]:
P

[10, -21.0, 12.0]